<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\Community\CommentController as CommunityCommentController;
use App\Http\Controllers\Api\Community\CommunityChatMessageController;
use App\Http\Controllers\Api\Community\PostController as CommunityPostController;
use App\Http\Controllers\Api\Jobs\HiringPostController;
use App\Http\Controllers\Api\Jobs\JobApplicationController;
use App\Http\Controllers\Api\Jobs\JobHunterProfileController;
use App\Http\Controllers\Api\Jobs\JobHunterInvitationController;
use App\Http\Controllers\Api\Jobs\SavedJobController;
use App\Http\Controllers\Api\Market\MerchantRegistrationController;
use App\Http\Controllers\Api\Market\MarketProductController;
use App\Http\Controllers\Api\Official\DashboardSummaryController;
use App\Http\Controllers\Api\Official\OfficialBarangaySetupController;
use App\Http\Controllers\Api\Official\EmergencyContactController;
use App\Http\Controllers\Api\Official\OfficialGovAgencyController;
use App\Http\Controllers\Api\Official\OfficialNotificationController;
use App\Http\Controllers\Api\Official\RecentActivityController;
use App\Http\Controllers\Api\Emergency\SharedLocationController;
use App\Http\Controllers\Api\Profile\ResidentProfileController;
use App\Http\Controllers\Api\Profile\ResidentRbiRecordController;
use App\Http\Controllers\Api\Services\ServiceRequestController;
use App\Http\Controllers\Api\LocationController;
use Illuminate\Support\Facades\Route;

Route::post('/register', [AuthController::class, 'register']);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/verify-otp', [AuthController::class, 'verifyOtp']);
Route::post('/resend-otp', [AuthController::class, 'resendOtp']);
Route::get('/locations', [LocationController::class, 'index']);
Route::get('/locations/address-directory', [LocationController::class, 'index']);
Route::get('/locations/directory', [LocationController::class, 'index']);

Route::middleware('auth:api')->group(function (): void {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::delete('/account', [AuthController::class, 'deleteAccount']);
    Route::post('/account/delete', [AuthController::class, 'deleteAccount']);
    Route::post('/activation/complete', [AuthController::class, 'completeActivation']);
    Route::get('/community/posts', [CommunityPostController::class, 'index']);
    Route::post('/community/posts', [CommunityPostController::class, 'store']);
    Route::get('/community/posts/{postId}', [CommunityPostController::class, 'show']);
    Route::patch('/community/posts/{postId}', [CommunityPostController::class, 'update']);
    Route::delete('/community/posts/{postId}', [CommunityPostController::class, 'destroy']);
    Route::post('/community/posts/{postId}/likes/toggle', [CommunityPostController::class, 'toggleLike']);
    Route::post('/community/posts/{postId}/comments', [CommunityCommentController::class, 'store']);
    Route::get('/community/chat/messages', [CommunityChatMessageController::class, 'index']);
    Route::post('/community/chat/messages', [CommunityChatMessageController::class, 'store']);
    Route::get('/jobs/hiring-posts', [HiringPostController::class, 'index']);
    Route::post('/jobs/hiring-posts', [HiringPostController::class, 'store']);
    Route::get('/jobs/hunter-profiles', [JobHunterProfileController::class, 'index']);
    Route::post('/jobs/hunter-profiles', [JobHunterProfileController::class, 'store']);
    Route::get('/jobs/invitations', [JobHunterInvitationController::class, 'index']);
    Route::post('/jobs/invitations', [JobHunterInvitationController::class, 'store']);
    Route::get('/jobs/applications', [JobApplicationController::class, 'index']);
    Route::post('/jobs/applications', [JobApplicationController::class, 'store']);
    Route::get('/jobs/saved', [SavedJobController::class, 'index']);
    Route::post('/jobs/saved/toggle', [SavedJobController::class, 'toggle']);
    Route::get('/market/merchant-registration', [MerchantRegistrationController::class, 'show']);
    Route::post('/market/merchant-registration', [MerchantRegistrationController::class, 'store']);
    Route::get('/market/products', [MarketProductController::class, 'index']);
    Route::post('/market/products', [MarketProductController::class, 'store']);
    Route::get('/services/requests', [ServiceRequestController::class, 'index']);
    Route::post('/services/requests', [ServiceRequestController::class, 'store']);
    Route::patch('/services/requests/{serviceRequestId}/status', [ServiceRequestController::class, 'updateStatus']);
    Route::get('/profile/resident', [ResidentProfileController::class, 'show']);
    Route::post('/profile/resident', [ResidentProfileController::class, 'upsert']);
    Route::get('/rbi/records', [ResidentRbiRecordController::class, 'index']);
    Route::post('/rbi/records', [ResidentRbiRecordController::class, 'upsert']);
    Route::patch('/rbi/records/{recordId}/verification', [ResidentRbiRecordController::class, 'updateVerificationStatus']);
    Route::get('/official/dashboard-summary', DashboardSummaryController::class);
    Route::get('/barangay/branding', [OfficialBarangaySetupController::class, 'branding']);
    Route::get('/official/barangay-setup', [OfficialBarangaySetupController::class, 'show']);
    Route::post('/official/barangay-setup', [OfficialBarangaySetupController::class, 'upsert']);
    Route::get('/official/recent-activity', RecentActivityController::class);
    Route::get('/official/gov-agencies', [OfficialGovAgencyController::class, 'index']);
    Route::post('/official/gov-agencies', [OfficialGovAgencyController::class, 'store']);
    Route::patch('/official/gov-agencies/{agencyId}', [OfficialGovAgencyController::class, 'update']);
    Route::delete('/official/gov-agencies/{agencyId}', [OfficialGovAgencyController::class, 'destroy']);
    Route::get('/official/notifications', [OfficialNotificationController::class, 'index']);
    Route::patch('/official/notifications/{notificationId}/read', [OfficialNotificationController::class, 'markRead']);
    Route::patch('/official/notifications/read-all', [OfficialNotificationController::class, 'markAllRead']);
    Route::get('/emergency/contacts', [EmergencyContactController::class, 'index']);
    Route::post('/emergency/contacts', [EmergencyContactController::class, 'store']);
    Route::patch('/emergency/contacts/{contactId}', [EmergencyContactController::class, 'update']);
    Route::delete('/emergency/contacts/{contactId}', [EmergencyContactController::class, 'destroy']);
    Route::get('/emergency/shared-locations', [SharedLocationController::class, 'index']);
    Route::get('/emergency/shared-location', [SharedLocationController::class, 'show']);
    Route::post('/emergency/shared-location', [SharedLocationController::class, 'store']);
});


